version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - logs:/armadion/logs
    command: /start
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis:7.0.5-alpine

  celery:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start-celeryworker
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web
  db:
    image: postgres:15.4-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5431:5432"
volumes:
  postgres_data:
  logs: