version: '3.3'

services:
  web:
    build: .
    restart: always
    command: gunicorn armadion.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/armadion/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:15.4-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - web
    ports:
      - 1337:80
    volumes:
      - static_volume:/armadion/staticfiles

volumes:
  postgres_data:
  static_volume: