version: '3.3'

services:
  web:
    image: evanstukalov/armadion:latest
    restart: always
    command: gunicorn armadion.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/armadion/staticfiles
      - media_volume:/armadion/mediafiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
  celery:
    restart: always
    image: evanstukalov/armadion:latest
    command: celery -A armadion worker -l info
    depends_on:
      - db
      - redis
      - web
      - nginx
  db:
    image: postgres:15.4-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - static_volume:/armadion/staticfiles
      - media_volume:/armadion/mediafiles
volumes:
  postgres_data:
  static_volume:
  media_volume: