name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Create credentials.json
      run: |
        echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json

    - name: Create .env
      run: |
        echo '${{ secrets.ENV_DEV }}' > .env
        echo '${{ secrets.ENV_PROD }}' > .env.prod


    - name: List files
      run: |
        ls -la

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8

    - name: Run mypy
      run: |
        mypy .

    - name: Run Tests
      env:
        SECRET_KEY: 69tgugtg%^fgJO&*&
        DB_NAME: mydb
        DB_USER: userdb
        DB_PASSWORD: password
        DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      run: |
        pytest

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3

        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: user/app:latest


